export const navbar = () => [
  {
    id: 1,
    name: "Home",
    link: "/",
  },
  {
    id: 2,
    name: "About",
    link: "/about",
  },
  {
    id: 3,
    name: "Menu",
    link: "/menu",
  },
];

export const heroli = () => [
  {
    id: 1,
    name: "Fresh Ingredients",
  },
  {
    id: 2,
    name: "Great Taste",
  },
  {
    id: 3,
    name: "Always",
  },
];

export const featuresData = () => [
  {
    id: 1,
    title: "Fresh & Quality Ingredients",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M11 20A7 7 0 0 1 4 13V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5a7 7 0 0 1-7 7Z" />
        <path d="M11 20v4" />
        <path d="M7 24h8" />
      </svg>
    ),
  },
  {
    id: 2,
    title: "Expert chefs & Authentic Taste",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M6 13.87A4 4 0 0 1 7.41 6a5.11 5.11 0 0 1 1.05-1.54 5 5 0 0 1 7.08 0A5.11 5.11 0 0 1 16.59 6 4 4 0 0 1 18 13.87V21H6Z" />
        <line x1="6" y1="17" x2="18" y2="17" />
      </svg>
    ),
  },
  {
    id: 3,
    title: "Fast & Reliable Delivery",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
        <circle cx="7" cy="17" r="2" />
        <path d="M9 17h6" />
        <circle cx="17" cy="17" r="2" />
      </svg>
    ),
  },
  {
    id: 4,
    title: "Hygienic & Safe Food",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
      </svg>
    ),
  },
];

export const menuData = () => [
  {
    id: 1,
    image: "/png/itemsimg.png",
    name: "Steamed Rice (250g)",
    price: "₹ 69.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 2,
    image: "/png/itemsimg.png",
    name: "Bengali Dal (250 ml)",
    price: "₹ 79.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 3,
    image: "/png/itemsimg.png",
    name: "Cholar Dal (250 ml)",
    price: "₹ 99.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 4,
    image: "/png/itemsimg.png",
    name: "Aloo Bhaja (120 g)",
    price: "₹ 79.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
];
export const choose = () => [
  {
    id: 1,
    svg: "/svg/good.svg",
    name: "Delicious & Authentic Food",
  },
  {
    id: 2,
    svg: "/svg/good.svg",
    name: "Crazy & Comfortable Ambience",
  },
  {
    id: 3,
    svg: "/svg/good.svg",
    name: "Friendly & Professional Staff",
  },
  {
    id: 4,
    svg: "/svg/good.svg",
    name: "Great value for money",
  },
];

export const galleryData = () => [
  { id: 1, image: "/png/mumose.png" },
  { id: 2, image: "/png/pizaa.png" },
  { id: 3, image: "/png/biriyani.png" },
  { id: 4, image: "/png/sek.png" },
  { id: 5, image: "/png/mumose.png" },
  { id: 6, image: "/png/pizaa.png" },
  { id: 7, image: "/png/biriyani.png" },
  { id: 8, image: "/png/sek.png" },
];

export const customerData = () => [
  {
    id: 1,
    image: "/svg/mahesh.svg",
    name: "Mahesh Yadav",
    rating: "4.8",
    review:
      "Absolutely delicious food, beautiful presentation, and a taste that keeps you coming back!",
  },
  {
    id: 2,
    image: "/svg/ram.svg",
    name: "Ram Yadav",
    rating: "4.8",
    review:
      "Fresh ingredients, rich flavors, and every bite felt absolutely perfect!",
  },
  {
    id: 3,
    image: "/svg/vikash.svg",
    name: "Vikash Yadav",
    rating: "4.8",
    review:
      "Amazing food, quick service, and a dining experience worth repeating!",
  },
];

export const footerCtaData = {
  subheading: "READY TO TASTE THE BEST",
  heading: "Order Your Favourite food Now",
  para: "Delicious food is just a click away. Place your order and enjoy the best flavours at your doorstep",
  btnText: "Order Now",
};

export const socialLinks = [
  {
    id: 1,
    link: "#",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
      </svg>
    ),
  },
  {
    id: 2,
    link: "#",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
        <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
      </svg>
    ),
  },
  {
    id: 3,
    link: "#",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
        <path d="m10 15 5-3-5-3z" />
      </svg>
    ),
  },
  {
    id: 4,
    link: "#",
    icon: (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M3 21l1.65-3.8a9 9 0 1 1 3.4 2.9L3 21" />
        <path d="M9 10a.5.5 0 0 0 1 0V9a.5.5 0 0 0-1 0v1a5 5 0 0 0 5 5h1a.5.5 0 0 0 0-1h-1a.5.5 0 0 0 0 1" />
      </svg>
    ),
  },
];

export const fullmenu = () => [
  {
    id: 1,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Steamed Rice (250g)",
    price: "₹ 69.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 2,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Dal (250 ml)",
    price: "₹ 79.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 3,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Cholar Dal (250 ml)",
    price: "₹ 99.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 4,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Aloo Bhaja (120 g)",
    price: "₹ 79.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 5,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Begun Bhaja (120 g)",
    price: "₹ 89.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 6,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Jhuri Aloo Bhaja (120 g)",
    price: "₹ 89.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 7,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Aloo Posto (250 g)",
    price: "₹ 199.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 8,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Aloo Phulkopi Dalna (250 g)",
    price: "₹ 119.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 9,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Dhokar Dalna (250 g)",
    price: "₹ 139.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 10,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Shukto (250 g)",
    price: "₹ 149.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 11,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mochar Ghonto (250 g)",
    price: "₹ 139.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 12,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mixed Bengali Vegetable (250 g)",
    price: "₹ 129.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 13,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Paneer Curry (250 g)",
    price: "₹ 159.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 14,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Rui Fish Curry (1 pc + 180 ml gravy)",
    price: "₹ 179.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 15,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Rui Kalia (1 pc + 180 ml gravy)",
    price: "₹ 199.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 16,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Doi Rui (1 pc + 180 ml gravy)",
    price: "₹ 199.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 17,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mustard Rui (1 pc + 180 ml gravy)",
    price: "₹ 209.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 18,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Katla Fish Curry (1 pc + 180 ml gravy)",
    price: "₹ 189.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 19,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Katla Kalia (1 pc + 180 ml gravy)",
    price: "₹ 209.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 20,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Pabda Jhal (1 pc + 180 ml gravy)",
    price: "₹ 229.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 21,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Pabda Shorshe (1 pc + 180 ml gravy)",
    price: "₹ 239.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 22,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Chingri Malai Curry (5 pcs + 200 ml gravy)",
    price: "₹ 299.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 23,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Chingri Shorshe (5 pcs + 200 ml gravy)",
    price: "₹ 289.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 24,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Chicken Jhol (4 pcs + 220 ml gravy)",
    price: "₹ 199.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 25,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Chicken Kosha (4 pcs + 180 ml gravy)",
    price: "₹ 219.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 26,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Chicken Dak Bungalow (4 pcs + 220 ml gravy)",
    price: "₹ 239.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 27,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Doi Chicken Bengali Style (4 pcs + 200 ml gravy)",
    price: "₹ 229.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 28,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Chicken Rezala (4 pcs + 200 ml gravy)",
    price: "₹ 239.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 29,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mutton Kosha (4 pcs + 180 ml gravy)",
    price: "₹ 299.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 30,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Mutton Jhol (4 pcs + 220 ml gravy)",
    price: "₹ 289.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 31,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mutton Dak Bungalow (4 pcs + 220 ml gravy)",
    price: "₹ 319.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 32,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mutton Rezala (4 pcs + 200 ml gravy)",
    price: "₹ 319.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 33,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Basanti Pulao (300 g)",
    price: "₹ 149.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 34,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Ghee Rice (300 g)",
    price: "₹ 129.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 35,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Matar Pulao (300 g)",
    price: "₹ 139.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 36,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bongo Veg Bengali Thali (1 thali)",
    price: "₹ 199.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 37,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bongo Fish Thali (1 thali)",
    price: "₹ 249.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 38,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bongo Chicken Thali (1 thali)",
    price: "₹ 279.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 39,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bongo Special Bengali Thali (1 thali)",
    price: "₹ 399.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 40,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bongo Mutton Thali (1 thali)",
    price: "₹ 349.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 41,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Mishti Doi (150 g)",
    price: "₹ 69.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 42,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Payesh (150 g)",
    price: "₹ 89.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 43,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Nolen Gur Payesh (150 g)",
    price: "₹ 99.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 44,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Rosogolla (2 pcs)",
    price: "₹ 69.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 45,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Sandesh (2 pcs)",
    price: "₹ 89.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 46,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Tomato Chutney (100 g)",
    price: "₹ 49.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 47,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Papad (2 pcs)",
    price: "₹ 30.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 48,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Green Salad (150 g)",
    price: "₹ 59.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 49,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Cucumber Raita (180 g)",
    price: "₹ 69.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 50,
    category: "Bengali Specials",
    image: "/png/itemsimg.png",
    name: "Bengali Cucumber-Onion Salad (150 g)",
    price: "₹ 59.00",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 51,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Veg Roll (1 pcs)",
    price: "₹79",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 52,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Paneer Roll (1 pcs)",
    price: "₹109",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 53,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Egg Paneer Roll (1 pcs)",
    price: "₹129",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 54,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Egg Roll (1 pcs)",
    price: "₹69",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 55,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Double Egg Roll (1 pcs)",
    price: "₹89",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 56,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Egg Cheese Roll (1 pcs)",
    price: "₹109",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 57,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Chicken Roll (1 pcs)",
    price: "₹109",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 58,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Double Chicken Roll (1 pcs)",
    price: "₹149",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 59,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Chicken Cheese Roll (1 pcs)",
    price: "₹139",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 60,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Chicken Mayo Roll (1 pcs)",
    price: "₹129",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 61,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Butter Chicken Roll (1 pcs)",
    price: "₹139",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 62,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Egg Chicken Roll (1 pcs)",
    price: "₹139",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    category: "Khathi Roll",
    id: 63,
    image: "/png/itemsimg.png",
    name: "Double Egg Chicken Roll (1 pcs)",
    price: "₹159",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 64,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Double Egg Double Chicken Roll (1 pcs)",
    price: "₹199",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 65,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Chilli Chicken Roll (1 pcs)",
    price: "₹139",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 66,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Schezwan Chicken Roll (1 pcs)",
    price: "₹139",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 67,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Chicken 65 Roll (1 pcs)",
    price: "₹149",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 68,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Chicken Reshmi Roll (1 pcs)",
    price: "₹169",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 69,
    category: "Khathi Roll",
    image: "/png/itemsimg.png",
    name: "Bongo Special Chicken Roll (1 pcs)",
    price: "₹189",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 70,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Veg Clear Soup",
    price: "₹119",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 71,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Sweet Corn Veg Soup",
    price: "₹129",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 72,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Hot & Sour Veg Soup",
    price: "₹139",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 73,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Veg Manchow Soup",
    price: "₹149",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 74,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Lemon Coriander Soup",
    price: "₹149",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 75,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Chicken Clear Soup",
    price: "₹159",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 76,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Sweet Corn Chicken Soup",
    price: "₹169",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 77,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Hot & Sour Chicken Soup",
    price: "₹179",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 78,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Chicken Manchow Soup",
    price: "₹189",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 79,
    category: "Soups",
    image: "/png/itemsimg.png",
    name: "Wonton Soup",
    price: "₹199",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 80,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Chilli Paneer",
    price: "₹229",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 81,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Dry Chilli Paneer",
    price: "₹239",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 82,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Paneer 65",
    price: "₹249",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 83,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Dragon Paneer",
    price: "₹259",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 84,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Crispy Baby Corn",
    price: "₹269",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 85,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Honey Chilli Potato",
    price: "₹279",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 86,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Crispy Corn",
    price: "₹289",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 87,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Veg Manchurian Dry",
    price: "₹299",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 88,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Veg Manchurian Gravy",
    price: "₹309",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 89,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Chilli Mushroom",
    price: "₹319",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 90,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Mushroom Pepper Fry",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 91,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Crispy Mushroom",
    price: "₹339",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 92,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Chilli Broccoli",
    price: "₹349",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 93,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Broccoli Pepper Garlic",
    price: "₹359",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 94,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Veg Spring Roll",
    price: "₹369",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 95,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Cheese Corn Balls",
    price: "₹379",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 96,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Veg Salt & Pepper",
    price: "₹389",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 97,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Veg Lollipop",
    price: "₹399",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 98,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Schezwan Veg",
    price: "₹409",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 99,
    category: "Veg Starters",
    image: "/png/itemsimg.png",
    name: "Mixed Veg Hot Garlic",
    price: "₹419",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 100,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Lollipop",
    price: "₹299",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 101,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Wings",
    price: "₹309",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 102,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Crispy Chicken",
    price: "₹319",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 103,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken 65",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 104,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Dragon Chicken",
    price: "₹339",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 105,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chilli Chicken Dry",
    price: "₹349",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 106,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chilli Chicken Gravy",
    price: "₹359",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 107,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Garlic Chicken",
    price: "₹369",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 108,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Pepper Chicken",
    price: "₹379",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 109,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Schezwan Chicken",
    price: "₹389",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 110,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Honey Chilli Chicken",
    price: "₹399",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 111,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Lemon Chicken",
    price: "₹409",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 112,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Manchurian Dry",
    price: "₹419",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 113,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Manchurian Gravy",
    price: "₹429",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 114,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Pakoda",
    price: "₹439",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 115,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Crispy Chicken Strips",
    price: "₹449",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 116,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Popcorn",
    price: "₹459",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 117,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Satay",
    price: "₹469",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 118,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Kung Pao Chicken",
    price: "₹479",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 119,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Black Pepper Chicken",
    price: "₹489",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 120,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Hot Garlic Chicken",
    price: "₹499",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 121,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Burnt Garlic Chicken",
    price: "₹509",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 122,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Tikka Chinese",
    price: "₹519",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 123,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Oriental Chicken",
    price: "₹529",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 124,
    category: "Chicken Starters",
    image: "/png/itemsimg.png",
    name: "Chicken Drumsticks",
    price: "₹539",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 125,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Chilli Fish",
    price: "₹339",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 126,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Fish Finger",
    price: "₹349",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 127,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Crispy Fish",
    price: "₹359",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 128,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Fish Manchurian",
    price: "₹369",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 129,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Pepper Fish",
    price: "₹379",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 130,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Garlic Fish",
    price: "₹389",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 131,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Schezwan Fish",
    price: "₹399",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 132,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Honey Chilli Fish",
    price: "₹409",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 133,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Salt & Pepper Fish",
    price: "₹419",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 134,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Chilli Prawns",
    price: "₹429",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 135,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Garlic Prawns",
    price: "₹439",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 136,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Pepper Prawns",
    price: "₹449",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 137,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Crispy Prawns",
    price: "₹459",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 138,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Dragon Prawns",
    price: "₹469",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 139,
    category: "Seafood",
    image: "/png/itemsimg.png",
    name: "Schezwan Prawns",
    price: "₹479",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 140,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Veg Steamed",
    price: "₹149",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 141,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Veg Fried",
    price: "₹159",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 142,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Veg Kurkure",
    price: "₹169",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 143,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Paneer Momos",
    price: "₹179",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 144,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Cheese Momos",
    price: "₹189",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 145,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Steamed",
    price: "₹199",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 146,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Fried",
    price: "₹209",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 147,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Kurkure",
    price: "₹219",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 148,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Cheese Momos",
    price: "₹229",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 149,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Tandoori Momos",
    price: "₹239",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 150,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Afghani Momos",
    price: "₹249",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 151,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chicken Peri Peri Momos",
    price: "₹259",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 152,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Schezwan Momos",
    price: "₹269",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 153,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Chilli Momos",
    price: "₹279",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 154,
    category: "Momos",
    image: "/png/itemsimg.png",
    name: "Jhol Momos",
    price: "₹289",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 155,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Veg Hakka",
    price: "₹189",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 156,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Egg Hakka",
    price: "₹199",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 157,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Chicken Hakka",
    price: "₹209",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 158,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Mixed Hakka",
    price: "₹219",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 159,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Veg Schezwan",
    price: "₹229",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 160,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Egg Schezwan",
    price: "₹239",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 161,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Chicken Schezwan",
    price: "₹249",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 162,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Mixed Schezwan",
    price: "₹259",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 163,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Burnt Garlic",
    price: "₹269",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 164,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Singapore",
    price: "₹279",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 165,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "American Chopsuey",
    price: "₹289",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 166,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Chinese Chopsuey",
    price: "₹299",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 167,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Hong Kong",
    price: "₹309",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 168,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Pan Fried",
    price: "₹319",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 169,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Triple Schezwan",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 170,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Garlic",
    price: "₹339",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 171,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Pepper",
    price: "₹349",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 172,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Mushroom",
    price: "₹359",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 173,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Seafood",
    price: "₹369",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 174,
    category: "Noodles",
    image: "/png/itemsimg.png",
    name: "Chicken Keema",
    price: "₹379",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 175,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Veg Fried Rice",
    price: "₹189",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 176,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Egg Fried Rice",
    price: "₹199",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 177,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Chicken Fried Rice",
    price: "₹209",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 178,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Mixed Fried Rice",
    price: "₹219",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 179,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Veg Schezwan Fried Rice",
    price: "₹229",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 180,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Chicken Schezwan Fried Rice",
    price: "₹239",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 181,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Burnt Garlic Fried Rice",
    price: "₹249",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 182,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Mushroom Fried Rice",
    price: "₹259",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 183,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Paneer Fried Rice",
    price: "₹269",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 184,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Triple Schezwan Rice",
    price: "₹279",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 185,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Hong Kong Fried Rice",
    price: "₹289",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 186,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Seafood Fried Rice",
    price: "₹299",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 187,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Garlic Fried Rice",
    price: "₹309",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 188,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Pepper Fried Rice",
    price: "₹319",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 189,
    category: "Fried Rice",
    image: "/png/itemsimg.png",
    name: "Oriental Fried Rice",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 190,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Veg Manchurian with Rice",
    price: "₹249",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 191,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Chilli Paneer with Rice",
    price: "₹269",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 192,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Chilli Chicken with Rice",
    price: "₹289",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 193,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Garlic Chicken with Rice",
    price: "₹309",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 194,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Chicken Manchurian with Rice",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 195,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Chilli Fish with Rice",
    price: "₹349",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 196,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Garlic Fish with Rice",
    price: "₹369",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 197,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Mixed Veg Hot Garlic with Rice",
    price: "₹389",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 198,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Kung Pao Chicken with Rice",
    price: "₹409",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 199,
    category: "Rice & Gravy",
    image: "/png/itemsimg.png",
    name: "Oriental Chicken with Rice",
    price: "₹429",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 200,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Veg Noodles+Chilli Paneer",
    price: "₹339",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 201,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Egg Noodles+Chilli Chicken",
    price: "₹379",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 202,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Chicken Fried Rice+Chicken Manchurian",
    price: "₹419",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 203,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Schezwan Rice+Dragon Chicken",
    price: "₹459",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 204,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Veg Fried Rice+Veg Manchurian",
    price: "₹339",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 205,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Chicken Noodles+Chicken Wings",
    price: "₹399",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 206,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Triple Rice+Chilli Chicken",
    price: "₹439",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 207,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Fish Fried Rice Combo",
    price: "₹469",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 208,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Momos+Soft Drink",
    price: "₹249",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 209,
    category: "Combos",
    image: "/png/itemsimg.png",
    name: "Family Combo",
    price: "₹899",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 210,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Bongo Special Chilli Chicken",
    price: "₹349",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 211,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Bongo Dragon Chicken",
    price: "₹359",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 212,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Bongo Mixed Sizzler",
    price: "₹499",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 213,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Chef Special Noodles",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 214,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Chef Special Fried Rice",
    price: "₹329",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 215,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Crispy Chicken Platter",
    price: "₹599",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 216,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Seafood Deluxe Combo",
    price: "₹699",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 217,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Chicken & Prawn Mix",
    price: "₹549",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 218,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Ultimate Chinese Feast",
    price: "₹799",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
  {
    id: 219,
    category: "Signature",
    image: "/png/itemsimg.png",
    name: "Party Pack",
    price: "₹999",
    svg: "/svg/star.svg",
    rating: "4.8",
  },
];
